stages:
  - quality
  - tests
  - install

code-quality:
  stage: quality
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install -y perl-modules
    - apt-get install -y libperl-critic-perl make
    - perlcritic --gentle "$CI_PROJECT_DIR"

make-test:
  stage: tests
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install -y perl-modules
    - apt-get install -y make
    - cd "$CI_PROJECT_DIR"
    - perl Makefile.PL
    - cover -test | tee devel-coverage.txt
    - grep "^Total" devel-coverage.txt | awk '{ print "(" $8 "%) covered" }'

make-install:
  stage: install
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install -y perl-modules
    - apt-get install -y make
    - cd "$CI_PROJECT_DIR"
    - perl Makefile.PL
    - make install

