stages:
  - tests

code:
  stage: tests
  script:
    - DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install -y libperl-critic-perl make
    - perl Makefile.PL
    - make test

